<?php

namespace rootio\Bundle\vmailmeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DeliveryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryRepository extends EntityRepository
{
}
